# 0. Integración, limpieza y preparación de los datos

In [1]:
import pandas as pd

ruta = "/Users/fran/Desktop/UCV Master /TFM/TFM VSC/Pedidos_22_26.xlsx"

df = pd.read_excel(ruta)

In [2]:
df.columns

Index(['Fecha Compra', 'Pedido #', 'Estado', 'Cliente', 'Tipo de cliente',
       'Productos', 'Artículos vendidos', 'Ventas netas', 'Atribución'],
      dtype='str')

In [3]:
df["Fecha Compra"].head(10)

0    1 junio, 2026junio 1, 2026
1    29 mayo, 2026mayo 29, 2026
2    29 mayo, 2026mayo 29, 2026
3    29 mayo, 2026mayo 29, 2026
4    29 mayo, 2026mayo 29, 2026
5    29 mayo, 2026mayo 29, 2026
6    27 mayo, 2026mayo 27, 2026
7    27 mayo, 2026mayo 27, 2026
8    27 mayo, 2026mayo 27, 2026
9    26 mayo, 2026mayo 26, 2026
Name: Fecha Compra, dtype: str

In [4]:
df["Fecha Compra"].drop_duplicates().head(10)

0     1 junio, 2026junio 1, 2026
1     29 mayo, 2026mayo 29, 2026
6     27 mayo, 2026mayo 27, 2026
9     26 mayo, 2026mayo 26, 2026
11    25 mayo, 2026mayo 25, 2026
17    22 mayo, 2026mayo 22, 2026
21    21 mayo, 2026mayo 21, 2026
22    20 mayo, 2026mayo 20, 2026
23    19 mayo, 2026mayo 19, 2026
24    18 mayo, 2026mayo 18, 2026
Name: Fecha Compra, dtype: str

In [5]:
df["Fecha Compra"] = (
    df["Fecha Compra"]
    .str.extract(r"^(.*?)\w+\s\d{1,2},\s\d{4}$")[0]
    .str.strip()
)

df["Fecha Compra"].head()

0    1 junio,
1    29 mayo,
2    29 mayo,
3    29 mayo,
4    29 mayo,
Name: Fecha Compra, dtype: str

In [6]:
df["Fecha Compra"].drop_duplicates().head(30)

0      1 junio,
1      29 mayo,
6      27 mayo,
9      26 mayo,
11     25 mayo,
17     22 mayo,
21     21 mayo,
22     20 mayo,
23     19 mayo,
24     18 mayo,
25     17 mayo,
26     16 mayo,
27     15 mayo,
30     14 mayo,
33     13 mayo,
35     12 mayo,
37     11 mayo,
45      9 mayo,
46      8 mayo,
48      7 mayo,
49      6 mayo,
50      5 mayo,
53      4 mayo,
55      3 mayo,
56      1 mayo,
57    30 abril,
58    28 abril,
60    26 abril,
63    24 abril,
65    22 abril,
Name: Fecha Compra, dtype: str

In [7]:
df["Fecha Compra"].unique()[:30]

<StringArray>
[ '1 junio,',  '29 mayo,',  '27 mayo,',  '26 mayo,',  '25 mayo,',  '22 mayo,',
  '21 mayo,',  '20 mayo,',  '19 mayo,',  '18 mayo,',  '17 mayo,',  '16 mayo,',
  '15 mayo,',  '14 mayo,',  '13 mayo,',  '12 mayo,',  '11 mayo,',   '9 mayo,',
   '8 mayo,',   '7 mayo,',   '6 mayo,',   '5 mayo,',   '4 mayo,',   '3 mayo,',
   '1 mayo,', '30 abril,', '28 abril,', '26 abril,', '24 abril,', '22 abril,']
Length: 30, dtype: str

In [8]:
import pandas as pd

ruta = "/Users/fran/Desktop/UCV Master /TFM/TFM VSC/Pedidos_22_26.xlsx"

df = pd.read_excel(ruta)

In [9]:
df["Fecha Compra"].head()

0    1 junio, 2026junio 1, 2026
1    29 mayo, 2026mayo 29, 2026
2    29 mayo, 2026mayo 29, 2026
3    29 mayo, 2026mayo 29, 2026
4    29 mayo, 2026mayo 29, 2026
Name: Fecha Compra, dtype: str

In [10]:
df["Fecha Compra"] = df["Fecha Compra"].str.extract(
    r"(\d{1,2}\s+\w+,\s+\d{4})"
)[0]

In [11]:
df["Fecha Compra"].head()

0    1 junio, 2026
1    29 mayo, 2026
2    29 mayo, 2026
3    29 mayo, 2026
4    29 mayo, 2026
Name: Fecha Compra, dtype: str

In [12]:
meses = {
    "enero": "01",
    "febrero": "02",
    "marzo": "03",
    "abril": "04",
    "mayo": "05",
    "junio": "06",
    "julio": "07",
    "agosto": "08",
    "septiembre": "09",
    "octubre": "10",
    "noviembre": "11",
    "diciembre": "12"
}

In [13]:
import re

def convertir_fecha(fecha):

    fecha = str(fecha).lower()

    patron = r"(\d{1,2})\s+(\w+),\s+(\d{4})"

    match = re.match(patron, fecha)

    if match:
        dia, mes, anio = match.groups()
        return f"{dia.zfill(2)}/{meses[mes]}/{anio}"

    return None

df["Fecha Compra"] = df["Fecha Compra"].apply(convertir_fecha)

In [14]:
df["Fecha Compra"].head()

0    01/06/2026
1    29/05/2026
2    29/05/2026
3    29/05/2026
4    29/05/2026
Name: Fecha Compra, dtype: str

## M1. Integración de información adicional

In [15]:
ruta_compras = "/Users/fran/Desktop/UCV Master /TFM/TFM VSC/Compras_2526_F&F.xlsx"

compras = pd.read_excel(ruta_compras)

## M2. Revisar estructura

In [16]:
compras.columns

Index(['Fecha de Compra', 'Número de Pedido', 'Taller', 'Fecha Taller',
       'Cantidad de Plazas', 'TARJETAS REGALO', 'Importe Total',
       'IMPORTE DEVOLUCIÓN', 'Método de Pago'],
      dtype='str')

In [17]:
compras.head()

,Fecha de Compra,Número de Pedido,Taller,Fecha Taller,Cantidad de Plazas,TARJETAS REGALO,Importe Total,IMPORTE DEVOLUCIÓN,Método de Pago
0,2024-11-18,43856526,Tarjeta Regalo,NaN,0,1.0,150.0,NaN,Visa
1,2025-01-01,43861545,Kimchi,2025-03-24 00:00:00,2,NaN,180.0,NaN,Bizum
2,2025-01-01,43861547,Tarjeta Regalo,NaN,0,1.0,90.0,NaN,Visa
3,2025-01-01,43861597,Tarjeta Regalo,NaN,0,0.0,0.0,NaN,Devolución
4,2025-01-01,43861549,Ramen,2025-03-28 00:00:00,2,NaN,162.0,NaN,Visa

## M3. Verificar duplicados de pedidos

In [19]:
compras["Número de Pedido"].duplicated().sum()

np.int64(121)

In [23]:
compras[compras["Número de Pedido"].duplicated(keep=False)].head(5)

,Fecha de Compra,Número de Pedido,Taller,Fecha Taller,Cantidad de Plazas,TARJETAS REGALO,Importe Total,IMPORTE DEVOLUCIÓN,Método de Pago
0,2024-11-18,43856526,Tarjeta Regalo,NaN,0,1.0,150.0,NaN,Visa
6,2025-01-02,43861602,Tarjeta Regalo,NaN,0,1.0,90.0,NaN,Visa
7,2025-01-02,43861602,Tarjeta Regalo,NaN,0,1.0,90.0,NaN,Visa
8,2025-01-02,43861602,Tarjeta Regalo,NaN,0,1.0,90.0,NaN,Visa
9,2025-01-02,43861602,Tarjeta Regalo,NaN,0,1.0,90.0,NaN,Visa

## M4. Ver cuántos productos faltan en tu dataset principal

In [24]:
df["Productos"].isna().sum()

np.int64(1184)

In [25]:
df[df["Productos"].isna()].head()

,Fecha Compra,Pedido #,Estado,Cliente,Tipo de cliente,Productos,Artículos vendidos,Ventas netas,Atribución
691,27/07/2025,43873390,Completado,Marta Galindo Sotos,New,NaN,1,"95,00 €",Fuente: Google
693,27/07/2025,43873378,Completado,Adrián March Gimeno,New,NaN,1,"0,00 €",Referido: Com.google.android.gm
695,26/07/2025,43873342,Completado,carla merani parrochia,New,NaN,1,"80,00 €",Orgánico: Google
696,25/07/2025,43873340,Completado,Claudia Vanacloig,Returning,NaN,1,"30,00 €",Fuente: Google
697,25/07/2025,43861597,Reembolsado,Alejandra Estepa Fernández,Returning,NaN,-1,"-70,00 €",Desconocido

## M5. Preparar tabla auxiliar para el merge

In [28]:
productos_aux = compras[["Número de Pedido", "Taller"]].drop_duplicates()

## M6. Unir ambos datasets

In [29]:
productos_aux = compras[["Número de Pedido", "Taller"]].copy()

productos_aux.rename(
    columns={"Número de Pedido": "Pedido #"},
    inplace=True
)

In [30]:
df = df.merge(
    productos_aux,
    on="Pedido #",
    how="left"
)

In [31]:
df["Productos"] = df["Productos"].fillna(df["Taller"])

In [32]:
df.drop(columns=["Taller"], inplace=True)

In [33]:
ruta_salida = "/Users/fran/Desktop/UCV Master /TFM/TFM VSC/Pedidos_22_26_Completado.xlsx"

df.to_excel(ruta_salida, index=False)

print("Archivo guardado correctamente")

Archivo guardado correctamente

In [34]:
df["Productos"] = df["Productos"].fillna(
    "Food & Fun, escenario culinario"
)

In [35]:
df["Productos"].isna().sum()

np.int64(0)

In [36]:
ruta_salida = "/Users/fran/Desktop/UCV Master /TFM/TFM VSC/Pedidos_22_26_Completado.xlsx"

df.to_excel(ruta_salida, index=False)

print("Archivo actualizado correctamente")

Archivo actualizado correctamente

# Conclusiones de la fase de integración y limpieza de datos

En esta fase se llevó a cabo el proceso de integración, depuración y preparación inicial de los datos procedentes de distintas fuentes de información de la empresa Food & Fun. El objetivo principal fue construir una base de datos única, consistente y preparada para las etapas posteriores de análisis y modelado.

Durante el proceso se realizaron las siguientes tareas:

Importación y revisión de los archivos originales proporcionados por la empresa.
Corrección y normalización de formatos de fecha para garantizar la consistencia temporal de los registros.
Identificación y tratamiento de registros incompletos o inconsistentes.
Integración de información procedente de diferentes archivos mediante el número de pedido como clave de unión.
Recuperación de información faltante sobre los talleres adquiridos a partir de fuentes complementarias.
Homogeneización de nombres de variables y formatos de almacenamiento.
Tratamiento de valores ausentes mediante procesos de imputación y enriquecimiento de datos.
Generación de un conjunto de datos consolidado listo para su explotación analítica.

Como resultado de esta fase se obtuvo un dataset limpio, estructurado y preparado para su utilización en las siguientes etapas del proyecto. Este conjunto de datos servirá como base para el análisis exploratorio, la identificación de patrones de demanda, el desarrollo de modelos predictivos y la posterior optimización de la planificación de talleres mediante técnicas de investigación operativa.

Finalmente, el dataset consolidado fue exportado para garantizar la trazabilidad del proceso y facilitar su reutilización en los distintos notebooks desarrollados durante el Trabajo Fin de Máster.

Archivo generado: Pedidos_22_26_Completado.xlsx